site_name: My Site
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode